##
## Makefile for Makefile in /home/bequig_s//workspace/test_perso/socket/client
## 
## Made by sebastien bequignon
## Login   <bequig_s@epitech.net>
## 
## Started on  Thu May  2 14:14:19 2013 sebastien bequignon
## Last update Thu May  2 14:16:26 2013 sebastien bequignon
##

all	: 
	gcc server/server.c server/server_work.c common/write.c common/read.c -o serveur
	gcc client/client.c common/read.c common/write.c -o clients